language: node_js
sudo: required
before_script:
  - npm install -g bower polymer-cli mocha
  - sudo mv /usr/bin/google-chrome /usr/bin/google-chrome-old
  - sudo mv /usr/bin/google-chrome-beta /usr/bin/google-chrome
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
script:
  - cd rtc-element
  - npm install
  - bower install
  - xvfb-run npm test
dist: trusty
